[package]
name = "carp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
panic = "unwind"

[profile.release]
panic = "unwind"

[dependencies]
termios = "0.3.3"
libc = "0.2.126"
sscanf = "0.2.1"
